---
- hosts: localhost
  remote_user: root
  vars:
    app_namespace: My_New_App
    github: daita/new_app
    app_id: my_app
    app_name: My Fresh New App
    dir: /home/maxence/my_new_app

  tasks:

    - name: create app directories
      file:
        state: directory
        path: "{{dir}}{{item.name}}"
      with_items:
        - { name: '/' }
        - { name: '/appinfo' }
        - { name: '/css' }
        - { name: '/img' }
        - { name: '/js' }
        - { name: '/lib' }
        - { name: '/lib/AppInfo' }
        - { name: '/lib/Controller' }
        - { name: '/lib/Exceptions' }
        - { name: '/lib/Service' }
        - { name: '/screenshots' }
        - { name: '/templates' }

    - name: generate app
      template:
        src: "tmpl{{item.name}}"
        dest: "{{dir}}{{item.name}}"
      with_items:
        - { name: '/appinfo/app.php' }
        - { name: '/appinfo/info.xml' }
        - { name: '/appinfo/routes.php' }
        - { name: '/css/navigate.css' }
        - { name: '/css/admin.css' }
        - { name: '/css/personal.css' }
        - { name: '/img/ruler.svg' }
        - { name: '/js/app.js' }
        - { name: '/js/admin.js' }
        - { name: '/js/personal.js' }
        - { name: '/lib/admin.php' }
        - { name: '/lib/personal.php' }
        - { name: '/lib/AppInfo/Application.php' }
        - { name: '/lib/Controller/NavigationController.php' }
        - { name: '/lib/Controller/SettingsController.php' }
        - { name: '/lib/Controller/SimpleController.php' }
        - { name: '/lib/Exceptions/SimpleException.php' }
        - { name: '/lib/Service/ConfigService.php' }
        - { name: '/lib/Service/MiscService.php' }
        - { name: '/lib/Service/SimpleService.php' }
        - { name: '/templates/navigate.php' }
        - { name: '/templates/settings.admin.php' }
        - { name: '/templates/settings.personal.php' }

